include: package:lints/recommended.yaml

linter:
  rules:
    camel_case_types: false
    file_names: false
    non_constant_identifier_names: false
    use_string_in_part_of_directives: false
    prefer_single_quotes: true
    prefer_final_fields: true