name: edwards25519
description: ed25519, where security meets simplicity in cryptography!!
version: 1.0.1
repository: https://github.com/justkawal/edwards25519

environment:
  sdk: ^3.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  convert: ^3.1.1
